
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autopoint libtool pkg-config libltdl-dev
          pip install buildozer
          pip install cython

      - name: Install Android SDK
        run: |
          sudo apt-get install -y openjdk-8-jdk-headless
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d android-sdk
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: yes|
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin
          buildozer init
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-pages-artifact@v3
        with:
          name: app.apk
          path: bin/*.apk