name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential ccache git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools \
            autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev libtiff-dev libpng-dev cmake

          pip3 install --upgrade pip
          pip3 install cython==0.29.36 virtualenv buildozer

      - name: Build APK
        run: yes|
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk