
name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autopoint libtool pkg-config libltdl-dev
          pip install buildozer
          pip install cython

      - name: Install Android SDK
        run: |
          sudo apt-get install -y openjdk-8-jdk-headless

      - name: Build APK
        run: yes|
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-pages-artifact@v3
        with:
          name: app.apk
          path: bin/*.apk