
name: my app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-11-jdk python3-pip python3-setuptools \
            git libffi-dev libssl-dev libjpeg-dev libfreetype6-dev \
            build-essential pkg-config libz-dev libncurses5 libncurses5-dev libsqlite3-dev libjpeg-dev

      - name: Install Buildozer
        run: pip3 install buildozer==1.5.0 cython==0.29.33

      - name: try build apk
        run:yes |
          autoreconf --force install 
          buildozer android debug --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: bin/*.apk
```