name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev libffi-dev libssl-dev

      - name: update 
        run: |
          autoupdate
      - name: Install Buildozer
        run: |
          pip3 install buildozer cython

      - name: Build APK
        run: yes|
          buildozer android debug deploy run 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
