name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake autopoint gcc git libtool make openjdk-17-jdk-headless patch pkg-config python3-dev python3-pip unzip zlib1g-dev

      - name: Install Buildozer
        run: |
          pip3 install buildozer cython

      - name: Build APK
        run: yes|
          buildozer android debug deploy --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
